---

- name: prerequisites
  include: prerequisites.yml

- name: dnf
  include: dnf.yml

- name: admin users
  include: admins.yml

- name: dns
  include: dns.yml
  when: 
  - enable_custom_dns

- name: swap file
  include: swap.yml
  when:
  - enable_swap

- name: time
  include: time.yml

- name: tuning
  include: tuning.yml

- name: utils
  include: utils.yml

- name: shl-tools
  include: shl_tools.yml

- name: handlers
  meta: flush_handlers
